spring:
  application:
    name: product-service

#  profiles:
#    active:
#      - dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root

server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


#jpa:
#  hibernate:
#    ddl-auto: update
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQLDialect